import { expect, test, type Page } from '@playwright/test'

async function navigateTo(page: Page, label: string, isMobile: boolean) {
  if (isMobile && ['退休制度', '行情更新', '預測設定', '資料與備份'].includes(label)) {
    await page.getByRole('button', { name: '更多功能' }).click()
    await page.getByRole('dialog').getByRole('button', { name: label }).click()
  } else {
    await page.getByRole('button', { name: label }).click()
  }
}

test.beforeEach(async ({ page }) => {
  await page.goto('/')
  await page.evaluate(async () => {
    await new Promise<void>((resolve, reject) => {
      const request = indexedDB.deleteDatabase('retirement-planner-public')
      request.onsuccess = () => resolve()
      request.onerror = () => reject(request.error)
      request.onblocked = () => undefined
    })
  })
  await page.reload()
})

test('展示資料不寫入本機資料庫，重新開啟後回到入口', async ({ page }) => {
  await page.getByRole('button', { name: '先使用展示資料體驗' }).click()
  await expect(page.locator('.projection-table tbody tr').last()).toBeVisible({ timeout: 15_000 })
  await expect(page.getByText('未來可能累積多少？')).toBeVisible()
  await page.reload()
  await expect(page.getByRole('button', { name: '快速試算我的未來資產' })).toBeVisible()
})

test('快速試算可儲存並在重新開啟後保留資料', async ({ page }) => {
  await page.getByRole('button', { name: '快速試算我的未來資產' }).click()
  await page.getByLabel('出生日期').fill('1990-01-01')
  await page.getByRole('button', { name: '下一步' }).click()
  await page.getByLabel('目前可投資資產總額（TWD）').fill('1000000')
  await page.getByLabel('每月預計投入金額（TWD）').fill('25000')
  await page.getByRole('button', { name: '下一步' }).click()
  await page.getByLabel('股票（%）').fill('70')
  await page.getByLabel('債券（%）').fill('20')
  await page.getByLabel('貨幣市場（%）').fill('0')
  await page.getByLabel('現金（%）').fill('10')
  await page.getByLabel('其他（%）').fill('0')
  await page.getByRole('button', { name: '開始查看結果' }).click()
  await expect(page.locator('.allocation-summary article').filter({ hasText: '股票' })).toContainText('70.0%', { timeout: 15_000 })
  await expect(page.getByText('未來可能累積多少？')).toBeVisible()
  await page.reload()
  await expect(page.getByText('我的退休規劃', { exact: true })).toBeVisible()
})

test('可切換至家庭資料並新增資產', async ({ page, isMobile }) => {
  await page.getByRole('button', { name: '先使用展示資料體驗' }).click()
  if (isMobile) await page.getByRole('button', { name: '家庭資料', exact: true }).click()
  else await page.getByRole('button', { name: '家庭資料', exact: true }).click()
  await page.getByRole('button', { name: '新增資產' }).click()
  await page.getByLabel('資產名稱').fill('緊急預備金')
  await page.getByLabel('目前價值（TWD）').fill('300000')
  await page.getByRole('button', { name: '儲存資產' }).click()
  await expect(page.getByText('緊急預備金')).toBeVisible()
  await page.getByRole('button', { name: '編輯 伴侶家庭可用資產' }).click()
  await page.getByText('進階資產設定（選填）', { exact: true }).click()
  await page.locator('select[name="retirementUsageScope"]').selectOption('personal')
  await page.getByRole('button', { name: '儲存資產' }).click()
  await expect(page.getByText('個人退休使用').first()).toBeVisible()
})

test('共同持分須為 100%，並可建立固定日期與報酬設定投入', async ({ page }) => {
  await page.getByRole('button', { name: '先使用展示資料體驗' }).click()
  await page.getByRole('button', { name: '家庭資料', exact: true }).click()
  await page.getByRole('button', { name: '新增資產' }).click()
  await page.getByLabel('資產名稱').fill('共同預備金')
  await page.getByLabel('目前價值（TWD）').fill('100000')
  await page.locator('select[name="ownershipType"]').selectOption('joint')
  await page.getByLabel('主要規劃人 A 持分（%）').fill('60')
  await page.getByLabel('伴侶 B 持分（%）').fill('39')
  await page.getByRole('button', { name: '儲存資產' }).click()
  await expect(page.getByText(/合計必須等於 100%/)).toBeVisible()
  await page.getByLabel('伴侶 B 持分（%）').fill('40')
  await page.getByRole('button', { name: '儲存資產' }).click()
  await expect(page.getByText('共同預備金')).toBeVisible()

  await page.getByRole('button', { name: '新增投入' }).click()
  await page.getByLabel('每月金額（TWD）').fill('5000')
  await page.getByLabel('停止規則').selectOption('fixedDate')
  await page.getByLabel('結束時間格式').selectOption('month')
  await page.getByLabel('固定停止月份').fill('2030-12')
  await page.getByLabel('投入目的').selectOption('profile')
  await page.getByRole('button', { name: '儲存投入' }).click()
  await expect(page.getByText(/2030-12 停止/)).toBeVisible()
})

test('資產可自訂情境報酬並重新套用系統預設', async ({ page }, testInfo) => {
  await page.getByRole('button', { name: '先使用展示資料體驗' }).click()
  await page.getByRole('button', { name: '家庭資料', exact: true }).click()
  await page.getByRole('button', { name: '編輯 退休投資帳戶' }).click()
  await expect(page.getByLabel('保守年報酬（%）')).toHaveCount(0)
  await page.getByLabel('自訂此資產的三種情境報酬').check()
  await page.getByLabel('保守年報酬（%）').fill('-1')
  await page.getByLabel('穩健年報酬（%）').fill('0')
  await page.getByLabel('比較樂觀年報酬（%）').fill('0.5')
  await page.screenshot({ path: testInfo.outputPath('asset-rates.png'), fullPage: true })
  await page.getByRole('button', { name: '儲存資產', exact: true }).click()
  await page.getByRole('button', { name: '家庭資料', exact: true }).click()
  await page.getByRole('button', { name: '編輯 退休投資帳戶' }).click()
  await expect(page.getByLabel('自訂此資產的三種情境報酬')).toBeChecked()
  await expect(page.getByLabel('比較樂觀年報酬（%）')).toHaveValue('0.5')
  await page.getByLabel('使用系統預設（stock）').check()
  await page.getByRole('button', { name: '儲存資產', exact: true }).click()
  await page.getByRole('button', { name: '編輯 退休投資帳戶' }).click()
  await expect(page.getByLabel('使用系統預設（stock）')).toBeChecked()
})

test('可維護收入、帳戶與持有部位，刪除帳戶不留下孤兒資料', async ({ page }) => {
  await page.getByRole('button', { name: '先使用展示資料體驗' }).click()
  await page.getByRole('button', { name: '家庭資料', exact: true }).click()
  await page.getByRole('button', { name: '收入', exact: true }).click()
  await page.getByLabel('名稱').fill('固定兼職收入')
  await page.getByLabel('每月金額（TWD）').fill('12000')
  await page.getByRole('button', { name: '儲存收入' }).click()
  const income = page.locator('article').filter({ hasText: '固定兼職收入' })
  await expect(income).toContainText('$12,000')
  await income.getByRole('button', { name: '編輯收入' }).click()
  await page.getByLabel('每月金額（TWD）').fill('15000')
  await page.getByRole('button', { name: '儲存收入' }).click()
  await expect(page.locator('article').filter({ hasText: '固定兼職收入' })).toContainText('$15,000')
  await page.locator('article').filter({ hasText: '固定兼職收入' }).getByRole('button', { name: '刪除收入' }).click()
  await expect(page.getByText('固定兼職收入')).toHaveCount(0)

  await page.getByRole('button', { name: '帳戶', exact: true }).click()
  await page.getByLabel('名稱').fill('測試證券帳戶')
  await page.getByLabel('帳戶類型').selectOption('brokerage')
  await page.getByRole('button', { name: '儲存帳戶' }).click()
  await page.getByRole('button', { name: '持有部位', exact: true }).click()
  await page.getByLabel('持有數量').fill('10')
  await page.getByRole('button', { name: '儲存持有部位' }).click()
  await expect(page.getByText(/測試證券帳戶－退休投資帳戶/)).toBeVisible()
  await page.locator('article').filter({ hasText: '測試證券帳戶' }).getByRole('button', { name: '刪除帳戶' }).click()
  await expect(page.getByText('尚未建立持有部位資料。')).toBeVisible()
})

test('Dashboard 完整呈現六個期間與三種情境，資產摘要移至家庭資料', async ({ page, isMobile }) => {
  await page.getByRole('button', { name: '先使用展示資料體驗' }).click()
  await expect(page.getByText('我現在的投資怎麼分配？')).toBeVisible({ timeout: 15_000 })
  await expect(page.getByText('未來可能累積多少？')).toBeVisible()
  await expect(page.locator('.projection-table tbody tr')).toHaveCount(1)
  await expect(page.getByLabel('查看時間').locator('option', { hasText: '目標退休時' })).toHaveCount(1)
  await expect(page.locator('.projection-table thead')).toContainText('實際年報酬')
  await page.getByLabel('同時查看所有時間點').check()
  await expect(page.locator('.projection-table tbody tr')).toHaveCount(7)
  for (const row of await page.locator('.projection-table tbody tr').all()) {
    await expect(row.locator('td')).toHaveCount(3)
    await expect(row.getByText(/今天購買力/)).toHaveCount(3)
  }
  if (!isMobile) await expect(page.getByRole('columnheader', { name: /比較樂觀/ })).toBeVisible()
  await expect(page.getByText('家庭完整資產摘要')).toHaveCount(0)
  await page.getByRole('button', { name: '家庭資料', exact: true }).click()
  await expect(page.getByText('家庭完整資產摘要')).toBeVisible()
})

test('可管理家庭成員並阻止不安全刪除', async ({ page }) => {
  await page.getByRole('button', { name: '快速試算我的未來資產' }).click()
  await page.getByLabel('出生日期').fill('1990-01-01')
  await page.getByRole('button', { name: '下一步' }).click()
  await page.getByLabel('目前可投資資產總額（TWD）').fill('1000000')
  await page.getByLabel('每月預計投入金額（TWD）').fill('10000')
  await page.getByRole('button', { name: '下一步' }).click()
  await page.getByLabel('股票（%）').fill('100')
  await page.getByLabel('債券（%）').fill('0')
  await page.getByLabel('貨幣市場（%）').fill('0')
  await page.getByLabel('現金（%）').fill('0')
  await page.getByLabel('其他（%）').fill('0')
  await page.getByRole('button', { name: '開始查看結果' }).click()
  await page.getByRole('button', { name: '家庭資料', exact: true }).click()
  await page.getByRole('button', { name: '新增成員' }).click()
  await page.getByLabel('姓名').fill('小林伴侶')
  await page.getByLabel('角色').selectOption('partner')
  await page.getByLabel('出生日期').fill('1992-01-01')
  await page.getByRole('button', { name: '儲存成員' }).click()
  await expect(page.getByText('小林伴侶')).toBeVisible()
  await page.getByRole('button', { name: '新增成員' }).click()
  await page.getByLabel('姓名').fill('第二位伴侶')
  await expect(page.getByLabel('角色').locator('option[value="partner"]')).toHaveJSProperty('disabled', true)
  await page.getByLabel('角色').selectOption('other')
  await page.getByLabel('出生日期').fill('2000-01-01')
  await page.getByRole('button', { name: '儲存成員' }).click()
  await expect(page.getByText('第二位伴侶')).toBeVisible()
  await expect(page.getByText(/主要規劃人 ·/)).toBeVisible()
})

test('Dashboard 顯示家庭財務概況與未提供資料狀態', async ({ page }) => {
  await page.getByRole('button', { name: '先使用展示資料體驗' }).click()
  const overview = page.getByRole('heading', { name: '家庭財務概況' }).locator('xpath=ancestor::section[1]')
  await expect(overview).toContainText('每月收入')
  await expect(overview).toContainText('每月平均支出')
  await expect(overview).toContainText('每月負債還款')
  await expect(overview).toContainText('每月投資')
  await expect(overview).toContainText('每月可支配餘額')
  await expect(overview).toContainText('尚未設定')
  await page.getByRole('button', { name: '查看／編輯家庭資料' }).click()
  await expect(page.getByRole('heading', { name: '家庭成員' })).toBeVisible()
})

test('計算名詞問號可開啟、切換並以 Escape 關閉說明', async ({ page }, testInfo) => {
  await page.getByRole('button', { name: '先使用展示資料體驗' }).click()
  const scenarioHelp = page.getByRole('button', { name: '說明：預設與自訂報酬情境' })
  await scenarioHelp.click()
  await expect(page.getByRole('dialog', { name: '預設與自訂報酬情境計算說明' })).toContainText('保守 = 原報酬率 − 2 個百分點')
  await expect(scenarioHelp).toHaveAttribute('aria-expanded', 'true')
  await page.screenshot({ path: testInfo.outputPath('calculation-help.png'), fullPage: false })

  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog', { name: '預設與自訂報酬情境計算說明' })).toHaveCount(0)
})

test('可保存一次性支出並重新產生預測', async ({ page, isMobile }) => {
  await page.getByRole('button', { name: '先使用展示資料體驗' }).click()
  await navigateTo(page, '預測設定', isMobile)
  await page.getByText('舊版退休試算資料（選填）', { exact: true }).click()
  await page.getByLabel('項目', { exact: true }).fill('整修支出')
  await page.getByLabel('月份', { exact: true }).fill('2045-06')
  await page.getByLabel('金額', { exact: true }).fill('500000')
  await page.getByRole('button', { name: '儲存設定' }).click()
  await page.getByRole('button', { name: '投資與退休預測' }).click()
  await expect(page.getByText('未來可能累積多少？')).toBeVisible({ timeout: 15_000 })
})

test('可依版本化規則估算勞保勞退並顯示於 Dashboard', async ({ page, isMobile }) => {
  await page.getByRole('button', { name: '先使用展示資料體驗' }).click()
  await navigateTo(page, '退休制度', isMobile)
  await expect(page.getByRole('link', { name: /投保資料與勞退查詢方式/ })).toBeVisible()
  const primaryPanel = page.locator('section.panel').filter({ hasText: '主要規劃人 A' })
  await expect(primaryPanel.getByText('勞保月領估算')).toBeVisible()
  await expect(primaryPanel.getByText(/首期月領約/)).toBeVisible()
  await primaryPanel.getByRole('button', { name: '儲存並估算' }).click()
  await expect(page.getByText('退休制度資料已儲存並重新估算。')).toBeVisible()
  await page.getByRole('button', { name: '投資與退休預測' }).click()
  await expect(page.getByText('勞保年金與勞退專戶')).toBeVisible({ timeout: 15_000 })
})

test('備份頁可以下載版本化 JSON', async ({ page, isMobile }) => {
  await page.getByRole('button', { name: '先使用展示資料體驗' }).click()
  await navigateTo(page, '資料與備份', isMobile)
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: '匯出 JSON 備份' }).click()
  const download = await downloadPromise
  expect(download.suggestedFilename()).toMatch(/^安心退休公開版備份_\d{4}-\d{2}-\d{2}\.json$/)
})

test('可設定投資組合並檢視配置偏離', async ({ page, isMobile }) => {
  await page.getByRole('button', { name: '先使用展示資料體驗' }).click()
  await navigateTo(page, '投資組合', isMobile)
  await expect(page.getByRole('heading', { name: /我的投資組合/ })).toBeVisible()
  await expect(page.getByText(/偏離 30.0 個百分點/)).toBeVisible()
  await page.getByLabel('股票（%）').fill('100')
  await page.getByLabel('債券（%）').fill('0')
  await page.getByLabel('現金（%）').fill('0')
  await page.getByRole('button', { name: '儲存投資組合' }).click()
  await expect(page.getByText('投資組合設定已儲存並重新計算。')).toBeVisible()
  await expect(page.getByText('所有配置均在允許偏離範圍內。')).toBeVisible()
  await page.getByRole('button', { name: '投資與退休預測' }).click()
  await expect(page.getByRole('heading', { name: '我現在的投資怎麼分配？' })).toBeVisible()
})

test('可建立、比較與刪除不修改正式資料的情境', async ({ page, isMobile }) => {
  await page.getByRole('button', { name: '先使用展示資料體驗' }).click()
  await navigateTo(page, '情境模擬', isMobile)
  await expect(page.locator('.scenario-table tbody tr').first()).toContainText('目前方案', { timeout: 15_000 })
  await expect(page.getByRole('row', { name: /勞退自提 6%/ })).toBeVisible()
  await page.getByLabel('方案名稱').fill('額外投入測試')
  await page.getByLabel('每月額外投入（TWD）').fill('5000')
  await page.getByLabel('每月額外投入（TWD）').press('Enter')
  await expect(page.getByRole('row', { name: /額外投入測試/ })).toBeVisible({ timeout: 15_000 })
  await page.getByRole('button', { name: '儲存此情境' }).click()
  const deleteScenario = page.getByRole('button', { name: '刪除方案 額外投入測試' })
  await deleteScenario.focus()
  await deleteScenario.press('Enter')
  await expect(page.getByRole('row', { name: /額外投入測試/ })).toHaveCount(0)
})

test('預測設定以單一 Accordion 顯示摘要、保留草稿並可恢復預設', async ({ page, isMobile }) => {
  await page.getByRole('button', { name: '先使用展示資料體驗' }).click()
  await navigateTo(page, '預測設定', isMobile)
  const stock = page.locator('.preset-card').filter({ hasText: '股票' }).getByRole('button').first()
  await expect(page.getByLabel('保守（%）')).toHaveCount(0)
  await stock.click()
  await page.getByLabel('穩健（%）').fill('7')
  await stock.click()
  await page.getByRole('button', { name: /債券.*2%.*3%.*4%/ }).click()
  await expect(page.getByLabel('穩健（%）')).toHaveValue('3')
  await page.getByRole('button', { name: /股票.*4%.*7%.*8%/ }).click()
  await expect(page.getByLabel('穩健（%）')).toHaveValue('7')
  await page.getByRole('button', { name: '恢復系統預設' }).click()
  await expect(page.getByLabel('穩健（%）')).toHaveValue('6')
})

test('可手動更新官方行情與匯率並同步重算資產', async ({ page, isMobile }) => {
  await page.route('**/api/market-data?*', async (route) => route.fulfill({ json: {
    quotes: [{ symbol: '0050', price: '70', currency: 'TWD', asOf: '2026-09-02', sourceId: 'twse-openapi-v1' }],
    rates: [{ fromCurrency: 'USD', toCurrency: 'TWD', rate: '31.666', asOf: '2026-08-31', sourceId: 'cbc-bp01d01' }, { fromCurrency: 'JPY', toCurrency: 'TWD', rate: '0.1984', asOf: '2026-08-31', sourceId: 'cbc-bp01d01' }, { fromCurrency: 'EUR', toCurrency: 'TWD', rate: '36.744', asOf: '2026-08-31', sourceId: 'cbc-bp01d01' }],
    errors: [], fetchedAt: '2026-09-03T00:00:00Z',
  } }))
  await page.getByRole('button', { name: '先使用展示資料體驗' }).click()
  await page.getByRole('button', { name: '家庭資料', exact: true }).click()
  await page.getByRole('button', { name: '編輯 退休投資帳戶' }).click()
  await page.getByLabel('使用市場行情更新目前價值').check()
  await page.getByLabel('上市代碼').fill('0050')
  await page.getByLabel('持有數量').fill('1000')
  await page.getByRole('button', { name: '儲存資產', exact: true }).click()
  await navigateTo(page, '行情更新', isMobile)
  await expect(page.getByText(/退休投資帳戶 · TWSE · 0050/)).toBeVisible()
  await page.getByRole('button', { name: '更新所有行情' }).click()
  await expect(page.getByText('行情與匯率更新完成。')).toBeVisible()
  await expect(page.getByText('70 TWD')).toBeVisible()
  await expect(page.getByText('31.6660')).toBeVisible()
  await page.getByRole('button', { name: '投資與退休預測' }).click()
  await expect(page.getByText(/^行情 \d/)).toBeVisible()
})

test('全球區域的 VT 可建立美股標的並以美元收盤價及匯率更新市值', async ({ page, isMobile }) => {
  await page.route('**/api/market-data?*', async (route) => route.fulfill({ json: {
    quotes: [], rates: [{ fromCurrency: 'USD', toCurrency: 'TWD', rate: '32', asOf: '2026-09-10', sourceId: 'cbc-ftd-day' }], errors: [], fetchedAt: '2026-09-11T00:00:00Z',
  } }))
  await page.route('https://www.stashgamma.com/api/dataapi/v1/eod/VT?*', async (route) => route.fulfill({ json: {
    bars: [{ date: '2026-09-10', close: 125 }],
  } }))
  await page.evaluate(() => localStorage.setItem('retirement-planner-us-eod-api-key-v1', 'sg_test_e2e'))
  await page.getByRole('button', { name: '先使用展示資料體驗' }).click()
  await page.getByRole('button', { name: '家庭資料', exact: true }).click()
  await page.getByRole('button', { name: '編輯 退休投資帳戶' }).click()
  await page.getByLabel('資產幣別').selectOption('USD')
  await expect(page.getByLabel('掛牌市場')).toHaveValue('US')
  await page.getByLabel('以美股日收盤價更新目前價值').check()
  await page.getByLabel('美股代號').fill('VT')
  await page.getByLabel('持有數量').fill('10')
  await page.getByLabel('匯率（1 USD 換多少 TWD）').fill('32')
  await page.getByText('進階資產設定（選填）').click()
  await page.getByLabel('地區').selectOption('global')
  await page.getByRole('button', { name: '儲存資產', exact: true }).click()
  await navigateTo(page, '行情更新', isMobile)
  await expect(page.getByText(/退休投資帳戶 · US · VT/)).toBeVisible()
  await page.getByRole('button', { name: '更新所有行情' }).click()
  await expect(page.getByText('行情與匯率更新完成。')).toBeVisible()
  await expect(page.getByText('125 USD')).toBeVisible()
  await page.getByRole('button', { name: '家庭資料', exact: true }).click()
  const asset = page.locator('.data-list article').filter({ hasText: '退休投資帳戶' }).first()
  await expect(asset).toContainText('USD 1,250')
  await expect(asset).toContainText(/40,000/)
})

test('視覺稽核截圖', async ({ page, isMobile }, testInfo) => {
  await page.screenshot({ path: testInfo.outputPath('onboarding.png') })
  await page.getByRole('button', { name: '先使用展示資料體驗' }).click()
  await expect(page.locator('.projection-table tbody tr').last()).toBeVisible({ timeout: 15_000 })
  await page.screenshot({ path: testInfo.outputPath('dashboard.png'), fullPage: true })
  await page.getByRole('button', { name: '家庭資料', exact: true }).click()
  await expect(page.getByRole('heading', { name: '家庭成員' })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('financial-data.png'), fullPage: true })
  await page.getByRole('button', { name: '新增資產' }).click()
  await page.locator('.editor-form').scrollIntoViewIfNeeded()
  await page.screenshot({ path: testInfo.outputPath('asset-editor.png') })
  await navigateTo(page, '預測設定', isMobile)
  await expect(page.getByRole('button', { name: '儲存設定' })).toBeVisible()
  await page.getByRole('heading', { name: '預測設定' }).last().scrollIntoViewIfNeeded()
  await expect(page.getByLabel('每月退休生活費')).not.toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('settings.png'), fullPage: true })
})

test('年份、範圍與自訂報酬可互動，勞退模式重新開啟仍保留', async ({ page, isMobile }, testInfo) => {
  await page.getByRole('button', { name: '先使用展示資料體驗' }).click()
  await page.getByLabel('查看時間').selectOption('25')
  await expect(page.locator('.projection-table tbody tr')).toHaveCount(1)
  await expect(page.locator('.projection-table tbody tr')).toContainText('25 年後')
  await expect(page.locator('.projection-breakdown')).toContainText('25 年後')
  await expect(page.locator('.recharts-line-curve')).toHaveCount(3)
  await expect(page.locator('.recharts-line-dot')).toHaveCount(21)
  const chartBox = await page.locator('.chart-wrap').boundingBox()
  const allocationBox = await page.locator('.allocation-summary').boundingBox()
  expect(allocationBox!.y).toBeLessThan(chartBox!.y)
  await page.getByText('自訂報酬情境（選填）', { exact: true }).click()
  await page.getByLabel('加入自訂情境').check()
  await page.getByLabel('穩健報酬再調整（百分點）').fill('2')
  await expect(page.locator('.projection-table tbody td')).toHaveCount(4)
  await page.getByLabel('查看範圍').selectOption('class:bond')
  await expect(page.locator('.projection-table tbody td').last()).toContainText('名目資產 $0')
  const singleAsset = await page.getByLabel('查看範圍').locator('option[value^="asset:"]').first().getAttribute('value')
  await page.getByLabel('查看範圍').selectOption(singleAsset!)
  await expect(page.locator('.projection-table tbody td').last()).not.toContainText('名目資產 $0')
  await expect(page.locator('.projection-table tbody td').last()).toContainText('勞退帳面累積價值（請領後固定） $0')
  await page.getByLabel('查看範圍').selectOption('all')
  await expect(page.locator('.projection-table tbody td').last()).not.toContainText('名目資產 $0')
  await page.locator('.projection-table').scrollIntoViewIfNeeded()
  await page.screenshot({ path: testInfo.outputPath('custom-projection.png'), fullPage: true })
  await navigateTo(page, '退休制度', isMobile)
  const primary = page.locator('section.panel').filter({ hasText: '主要規劃人 A' })
  await primary.getByText(/勞保老年年金設定/).click()
  await primary.getByText(/勞退新制退休金設定/).click()
  await primary.getByLabel('勞退請領模式').selectOption('lumpSum')
  await primary.getByRole('button', { name: '儲存並估算' }).click()
  await expect(primary.getByText(/選擇一次領/)).toBeVisible()
  await primary.getByLabel('目前勞保投保年資（年）').fill('20.5')
  await primary.getByLabel('勞退請領模式').selectOption('monthly')
  await primary.getByRole('button', { name: '儲存並估算' }).click()
  await expect(primary.getByText(/目前 20.5 年 ＋ 預估續保/)).toBeVisible()
  await expect(primary.getByText(/首期月領約/)).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('pension-monthly.png'), fullPage: true })
})

test('行動版導覽、觸控尺寸與漸進式資產表單符合 Mobile First 規格', async ({ page, isMobile }) => {
  test.skip(!isMobile, '此驗證只套用行動與平板專案')
  await page.getByRole('button', { name: '先使用展示資料體驗' }).click()
  const bottomNav = page.getByRole('navigation', { name: '行動版主要功能' })
  await expect(bottomNav.getByRole('button')).toHaveCount(5)
  for (const label of ['投資與退休預測', '家庭資料', '投資組合', '情境模擬', '更多功能']) {
    const box = await bottomNav.getByRole('button', { name: label }).boundingBox()
    expect(box?.height).toBeGreaterThanOrEqual(44)
  }
  await bottomNav.getByRole('button', { name: '更多功能' }).click()
  const menu = page.getByRole('dialog', { name: '更多功能' })
  await expect(menu.getByRole('button', { name: '退休制度' })).toBeVisible()
  await expect(menu.getByRole('button', { name: '行情更新' })).toBeVisible()
  await expect(menu.getByRole('button', { name: '預測設定' })).toBeVisible()
  await expect(menu.getByRole('button', { name: '資料與備份' })).toBeVisible()
  await menu.getByRole('button', { name: '關閉更多功能' }).click()

  await bottomNav.getByRole('button', { name: '家庭資料' }).click()
  await expect(page.locator('#main-content')).toBeFocused()
  await page.getByRole('button', { name: '新增資產' }).click()
  const predictionSettings = page.locator('.asset-prediction-settings')
  await expect(predictionSettings).not.toHaveAttribute('open', '')
  await page.locator('select[name="assetType"]').selectOption('etf')
  await expect(predictionSettings).toHaveAttribute('open', '')
  await expect(page.getByText('使用市場行情更新目前價值')).toBeVisible()
  expect(await page.getByLabel('資產名稱').evaluate((input) => Number.parseFloat(getComputedStyle(input).fontSize))).toBeGreaterThanOrEqual(16)
  const portraitOverflow = await page.evaluate(() => Array.from(document.querySelectorAll<HTMLElement>('body *')).filter((element) => element.getBoundingClientRect().right > document.documentElement.clientWidth + 1).map((element) => ({ tag: element.tagName, className: element.className, right: Math.round(element.getBoundingClientRect().right) })).slice(0, 10))
  expect(portraitOverflow).toEqual([])
})

test('小螢幕、橫向與放大文字沒有水平溢位', async ({ page }) => {
  await page.setViewportSize({ width: 375, height: 667 })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.getByRole('button', { name: '先使用展示資料體驗' }).click()
  await expect(page.locator('.projection-table tbody tr').last()).toBeVisible({ timeout: 15_000 })
  const portraitOverflow = await page.evaluate(() => Array.from(document.querySelectorAll<HTMLElement>('body *')).filter((element) => element.getBoundingClientRect().right > document.documentElement.clientWidth + 1).map((element) => ({ tag: element.tagName, className: element.className, right: Math.round(element.getBoundingClientRect().right) })).slice(0, 10))
  expect(portraitOverflow).toEqual([])

  await page.setViewportSize({ width: 844, height: 390 })
  await page.evaluate(() => { document.documentElement.style.fontSize = '20px' })
  const landscapeOverflow = await page.evaluate(() => Array.from(document.querySelectorAll<HTMLElement>('body *')).filter((element) => element.getBoundingClientRect().right > document.documentElement.clientWidth + 1).map((element) => ({ tag: element.tagName, className: element.className, right: Math.round(element.getBoundingClientRect().right) })).slice(0, 10))
  expect(landscapeOverflow).toEqual([])
  await expect(page.getByRole('button', { name: '家庭資料', exact: true })).toBeVisible()
})

test('PWA Service Worker 可離線重新開啟既有規劃', async ({ page, context, browserName }) => {
  test.skip(browserName === 'webkit', 'Playwright WebKit 不提供 Service Worker 離線測試環境')
  await page.getByRole('button', { name: '快速試算我的未來資產' }).click()
  await page.getByLabel('出生日期').fill('1990-01-01')
  await page.getByRole('button', { name: '下一步' }).click()
  await page.getByLabel('目前可投資資產總額（TWD）').fill('1000000')
  await page.getByLabel('每月預計投入金額（TWD）').fill('0')
  await page.getByRole('button', { name: '下一步' }).click()
  await page.getByLabel('股票（%）').fill('100')
  await page.getByLabel('債券（%）').fill('0')
  await page.getByLabel('貨幣市場（%）').fill('0')
  await page.getByLabel('現金（%）').fill('0')
  await page.getByLabel('其他（%）').fill('0')
  await page.getByRole('button', { name: '開始查看結果' }).click()
  await expect(page.locator('.projection-table tbody tr').last()).toBeVisible({ timeout: 15_000 })
  await page.evaluate(() => navigator.serviceWorker.ready)
  await context.setOffline(true)
  await page.reload()
  await expect(page.getByText('我的退休規劃', { exact: true })).toBeVisible()
  await context.setOffline(false)
})



test('第一階段：USD 與投入名稱期間可保存，單筆預測與請領狀態可切換', async ({ page, isMobile }, testInfo) => {
  await page.getByRole('button', { name: '先使用展示資料體驗' }).click()
  await expect(page.locator('.projection-table tbody tr')).toHaveCount(1)
  await expect(page.locator('.projection-table')).toContainText('尚未符合請領條件')
  await page.getByRole('button', { name: '家庭資料', exact: true }).click()
  await page.getByRole('button', { name: '編輯 退休投資帳戶' }).click()
  await page.getByLabel('資產幣別').selectOption('USD')
  await page.getByLabel('目前價值（USD）').fill('1000')
  await page.getByLabel('匯率（1 USD 換多少 TWD）').fill('32')
  await page.getByRole('button', { name: '儲存資產' }).click()
  await expect(page.locator('.data-list article').filter({ hasText: '退休投資帳戶' }).first()).toContainText('USD')
  await page.getByRole('button', { name: '新增投入' }).click()
  await page.getByLabel('投入名稱（選填）').fill('年度薪資投入')
  await page.getByLabel('每月金額（TWD）').fill('100')
  await page.getByLabel('開始日期').fill('2026-01-01')
  await page.getByLabel('停止規則').selectOption('fixedDate')
  await page.getByRole('textbox', { name: /^結束日期/ }).fill('2026-12-31')
  await page.getByRole('button', { name: '儲存投入' }).click()
  await expect(page.getByText('年度薪資投入', { exact: true })).toBeVisible()
  await expect(page.getByText(/2026-12-31 結束/)).toBeVisible()
  await page.getByRole('button', { name: '投資與退休預測', exact: true }).click()
  const scope = page.getByLabel('查看範圍')
  const option = await scope.locator('option[value^="asset:"]').first().getAttribute('value')
  await scope.selectOption(option!)
  await expect(page.locator('.projection-table tbody td')).toHaveCount(3)
  await expect(page.locator('.projection-table tbody td').first()).not.toContainText('名目資產 $0')
  await page.screenshot({ path: testInfo.outputPath('stage-one-scope.png'), fullPage: true })
  await scope.selectOption('all')
  await expect(page.locator('.projection-table')).toContainText('尚未符合請領條件')
  await page.getByLabel('查看時間').selectOption('35')
  await expect(page.locator('.projection-table')).toContainText('已達一般請領年齡')
  await navigateTo(page, '行情更新', isMobile)
  await expect(page.getByRole('button', { name: '更新所有行情' })).toBeEnabled()
})
