import { expect, test } from '@playwright/test'

test.beforeEach(async ({ page }) => {
  await page.goto('/')
  await page.evaluate(async () => {
    await new Promise<void>((resolve, reject) => {
      const request = indexedDB.deleteDatabase('retirement-planner-pwa')
      request.onsuccess = () => resolve()
      request.onerror = () => reject(request.error)
      request.onblocked = () => resolve()
    })
  })
  await page.reload()
})

test('可載入展示資料、完成計算並在重新開啟後保留資料', async ({ page }) => {
  await page.getByRole('button', { name: '先使用展示資料體驗' }).click()
  await expect(page.getByRole('heading', { name: /35 年後約/ })).toBeVisible({ timeout: 15_000 })
  await expect(page.getByText('固定期間資產預估')).toBeVisible()
  await page.reload()
  await expect(page.getByText('林家退休計畫')).toBeVisible()
  await expect(page.getByRole('heading', { name: /35 年後約/ })).toBeVisible({ timeout: 15_000 })
})

test('可切換至家庭資料並新增資產', async ({ page, isMobile }) => {
  await page.getByRole('button', { name: '先使用展示資料體驗' }).click()
  if (isMobile) await page.getByRole('button', { name: '家庭資料' }).click()
  else await page.getByRole('button', { name: '家庭資料' }).click()
  await page.getByRole('button', { name: '新增資產' }).click()
  await page.getByLabel('資產名稱').fill('緊急預備金')
  await page.getByLabel('目前價值（TWD）').fill('300000')
  await page.getByRole('button', { name: '儲存資產' }).click()
  await expect(page.getByText('緊急預備金')).toBeVisible()
  await page.getByRole('button', { name: '編輯 伴侶家庭可用資產' }).click()
  await page.locator('select[name="retirementUsageScope"]').selectOption('personal')
  await page.getByRole('button', { name: '儲存資產' }).click()
  await expect(page.getByText('個人退休使用').first()).toBeVisible()
})

test('共同持分須為 100%，並可建立固定日期與報酬設定投入', async ({ page }) => {
  await page.getByRole('button', { name: '先使用展示資料體驗' }).click()
  await page.getByRole('button', { name: '家庭資料' }).click()
  await page.getByRole('button', { name: '新增資產' }).click()
  await page.getByLabel('資產名稱').fill('共同預備金')
  await page.getByLabel('目前價值（TWD）').fill('100000')
  await page.locator('select[name="ownershipType"]').selectOption('joint')
  await page.getByLabel('主要規劃人 A 持分（%）').fill('60')
  await page.getByLabel('伴侶 B 持分（%）').fill('39')
  await page.getByRole('button', { name: '儲存資產' }).click()
  await expect(page.getByText(/合計必須等於 100%/)).toBeVisible()
  await page.getByLabel('伴侶 B 持分（%）').fill('40')
  await page.getByRole('button', { name: '儲存資產' }).click()
  await expect(page.getByText('共同預備金')).toBeVisible()

  await page.getByRole('button', { name: '新增投入' }).click()
  await page.getByLabel('每月金額（TWD）').fill('5000')
  await page.getByLabel('停止規則').selectOption('fixedDate')
  await page.getByLabel('固定停止月份').fill('2030-12')
  await page.getByLabel('投入目的').selectOption('profile')
  await page.getByRole('button', { name: '儲存投入' }).click()
  await expect(page.getByText(/2030-12 停止/)).toBeVisible()
})

test('可維護收入、帳戶與持有部位，刪除帳戶不留下孤兒資料', async ({ page }) => {
  await page.getByRole('button', { name: '先使用展示資料體驗' }).click()
  await page.getByRole('button', { name: '家庭資料' }).click()
  await page.getByRole('button', { name: '收入', exact: true }).click()
  await page.getByLabel('名稱').fill('固定兼職收入')
  await page.getByLabel('每月金額（TWD）').fill('12000')
  await page.getByRole('button', { name: '儲存收入' }).click()
  const income = page.locator('article').filter({ hasText: '固定兼職收入' })
  await expect(income).toContainText('$12,000')
  await income.getByRole('button', { name: '編輯收入' }).click()
  await page.getByLabel('每月金額（TWD）').fill('15000')
  await page.getByRole('button', { name: '儲存收入' }).click()
  await expect(page.locator('article').filter({ hasText: '固定兼職收入' })).toContainText('$15,000')
  await page.locator('article').filter({ hasText: '固定兼職收入' }).getByRole('button', { name: '刪除收入' }).click()
  await expect(page.getByText('固定兼職收入')).toHaveCount(0)

  await page.getByRole('button', { name: '帳戶', exact: true }).click()
  await page.getByLabel('名稱').fill('測試證券帳戶')
  await page.getByLabel('帳戶類型').selectOption('brokerage')
  await page.getByRole('button', { name: '儲存帳戶' }).click()
  await page.getByRole('button', { name: '持有部位', exact: true }).click()
  await page.getByLabel('持有數量').fill('10')
  await page.getByRole('button', { name: '儲存持有部位' }).click()
  await expect(page.getByText(/測試證券帳戶－退休投資帳戶/)).toBeVisible()
  await page.locator('article').filter({ hasText: '測試證券帳戶' }).getByRole('button', { name: '刪除帳戶' }).click()
  await expect(page.getByText('尚未建立持有部位資料。')).toBeVisible()
})

test('Dashboard 顯示配置、固定期間三情境、購買力與次要資產摘要', async ({ page }) => {
  await page.getByRole('button', { name: '先使用展示資料體驗' }).click()
  await expect(page.getByText('目前投資組合配置')).toBeVisible({ timeout: 15_000 })
  await expect(page.getByText('固定期間資產預估')).toBeVisible()
  await expect(page.getByRole('columnheader', { name: /保守/ })).toBeVisible()
  await expect(page.getByRole('columnheader', { name: /穩健/ })).toBeVisible()
  await expect(page.getByRole('columnheader', { name: /樂觀/ })).toBeVisible()
  await expect(page.getByText('完整資產摘要')).toBeVisible()
  const projectionHeading = await page.getByRole('heading', { name: /35 年後約/ }).textContent()
  await page.getByRole('button', { name: '主要規劃人', exact: true }).click()
  await expect(page.getByRole('heading', { name: /35 年後約/ })).toHaveText(projectionHeading ?? '')
})

test('計算名詞問號可開啟、切換並以 Escape 關閉說明', async ({ page }, testInfo) => {
  await page.getByRole('button', { name: '先使用展示資料體驗' }).click()
  const scenarioHelp = page.getByRole('button', { name: '說明：保守／穩健／樂觀情境' })
  await scenarioHelp.click()
  await expect(page.getByRole('dialog', { name: '保守／穩健／樂觀情境計算說明' })).toContainText('保守 = 原報酬率 − 2%')
  await expect(scenarioHelp).toHaveAttribute('aria-expanded', 'true')
  await page.screenshot({ path: testInfo.outputPath('calculation-help.png'), fullPage: false })

  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog', { name: '保守／穩健／樂觀情境計算說明' })).toHaveCount(0)
})

test('可保存一次性支出並重新產生預測', async ({ page }) => {
  await page.getByRole('button', { name: '先使用展示資料體驗' }).click()
  await page.getByRole('button', { name: '預測設定' }).click()
  await page.getByLabel('項目', { exact: true }).fill('整修支出')
  await page.getByLabel('月份', { exact: true }).fill('2045-06')
  await page.getByLabel('金額', { exact: true }).fill('500000')
  await page.getByRole('button', { name: '儲存設定' }).click()
  await page.getByRole('button', { name: '投資與退休預測' }).click()
  await expect(page.getByText('固定期間資產預估')).toBeVisible({ timeout: 15_000 })
})

test('可依版本化規則估算勞保勞退並顯示於 Dashboard', async ({ page }) => {
  await page.getByRole('button', { name: '先使用展示資料體驗' }).click()
  await page.getByRole('button', { name: '退休制度' }).click()
  await expect(page.getByText('tw-labor-rules-2026-08-20')).toBeVisible()
  const primaryPanel = page.locator('section.panel').filter({ hasText: '主要規劃人 A' })
  await expect(primaryPanel.getByText('勞保月領估算')).toBeVisible()
  await expect(primaryPanel.getByText(/首期月領約/)).toBeVisible()
  await primaryPanel.getByRole('button', { name: '儲存並估算' }).click()
  await expect(page.getByText('退休制度資料已儲存並重新估算。')).toBeVisible()
  await page.getByRole('button', { name: '投資與退休預測' }).click()
  await expect(page.getByText('勞保年金與勞退專戶')).toBeVisible({ timeout: 15_000 })
})

test('備份頁可以下載版本化 JSON', async ({ page }) => {
  await page.getByRole('button', { name: '先使用展示資料體驗' }).click()
  await page.getByRole('button', { name: '備份還原' }).click()
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: '匯出 JSON 備份' }).click()
  const download = await downloadPromise
  expect(download.suggestedFilename()).toMatch(/^退休規劃備份_\d{4}-\d{2}-\d{2}\.json$/)
})

test('可設定投資組合並檢視配置偏離', async ({ page }) => {
  await page.getByRole('button', { name: '先使用展示資料體驗' }).click()
  await page.getByRole('button', { name: '投資組合' }).click()
  await expect(page.getByRole('heading', { name: /投資組合與再平衡/ })).toBeVisible()
  await expect(page.getByText(/偏離 30.0 個百分點/)).toBeVisible()
  await page.getByLabel('股票（%）').fill('100')
  await page.getByLabel('債券（%）').fill('0')
  await page.getByLabel('現金（%）').fill('0')
  await page.getByRole('button', { name: '儲存投資組合' }).click()
  await expect(page.getByText('投資組合設定已儲存並重新計算。')).toBeVisible()
  await expect(page.getByText('所有配置均在允許偏離範圍內。')).toBeVisible()
  await page.getByRole('button', { name: '投資與退休預測' }).click()
  await expect(page.getByRole('heading', { name: '目前投資組合配置' })).toBeVisible()
})

test('可建立、比較與刪除不修改正式資料的情境', async ({ page }) => {
  await page.getByRole('button', { name: '先使用展示資料體驗' }).click()
  await page.getByRole('button', { name: '情境比較' }).click()
  await expect(page.getByRole('row', { name: /目前投入計畫/ })).toBeVisible({ timeout: 15_000 })
  await expect(page.getByRole('row', { name: /勞退自提 6%/ })).toBeVisible()
  await page.getByLabel('方案名稱').fill('額外投入測試')
  await page.getByLabel('每月額外投入（TWD）').fill('5000')
  await page.getByLabel('每月額外投入（TWD）').press('Enter')
  await expect(page.getByRole('row', { name: /額外投入測試/ })).toBeVisible({ timeout: 15_000 })
  const deleteScenario = page.getByRole('button', { name: '刪除方案 額外投入測試' })
  await deleteScenario.focus()
  await deleteScenario.press('Enter')
  await expect(page.getByRole('row', { name: /額外投入測試/ })).toHaveCount(0)
})

test('可手動更新官方行情與匯率並同步重算資產', async ({ page }) => {
  await page.route('**/api/market-data?*', async (route) => route.fulfill({ json: {
    quotes: [{ symbol: '0050', price: '70', currency: 'TWD', asOf: '2026-09-02', sourceId: 'twse-openapi-v1' }],
    rates: [{ fromCurrency: 'USD', toCurrency: 'TWD', rate: '31.666', asOf: '2026-08-31', sourceId: 'cbc-bp01d01' }, { fromCurrency: 'JPY', toCurrency: 'TWD', rate: '0.1984', asOf: '2026-08-31', sourceId: 'cbc-bp01d01' }, { fromCurrency: 'EUR', toCurrency: 'TWD', rate: '36.744', asOf: '2026-08-31', sourceId: 'cbc-bp01d01' }],
    errors: [], fetchedAt: '2026-09-03T00:00:00Z',
  } }))
  await page.getByRole('button', { name: '先使用展示資料體驗' }).click()
  await page.getByRole('button', { name: '行情更新' }).click()
  const firstAsset = page.locator('fieldset').filter({ hasText: '退休投資帳戶' })
  await firstAsset.getByLabel('上市代碼').fill('0050')
  await firstAsset.getByLabel('持有數量').fill('1000')
  await page.getByRole('button', { name: '儲存標的設定' }).click()
  await page.getByRole('button', { name: '更新股票、ETF 與匯率' }).click()
  await expect(page.getByText('行情與匯率更新完成。')).toBeVisible()
  await expect(page.getByText('70 TWD')).toBeVisible()
  await expect(page.getByText('31.6660')).toBeVisible()
  await page.getByRole('button', { name: '投資與退休預測' }).click()
  await expect(page.getByText(/^行情 \d/)).toBeVisible()
})

test('視覺稽核截圖', async ({ page }, testInfo) => {
  await page.getByRole('button', { name: '先使用展示資料體驗' }).click()
  await expect(page.getByRole('heading', { name: /35 年後約/ })).toBeVisible({ timeout: 15_000 })
  await page.screenshot({ path: testInfo.outputPath('dashboard.png'), fullPage: true })
  await page.getByRole('button', { name: '家庭資料' }).click()
  await expect(page.getByRole('heading', { name: '家庭成員' })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('financial-data.png'), fullPage: true })
})

test('小螢幕、橫向與放大文字沒有水平溢位', async ({ page }) => {
  await page.setViewportSize({ width: 375, height: 667 })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.getByRole('button', { name: '先使用展示資料體驗' }).click()
  await expect(page.getByRole('heading', { name: /35 年後約/ })).toBeVisible({ timeout: 15_000 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true)

  await page.setViewportSize({ width: 844, height: 390 })
  await page.evaluate(() => { document.documentElement.style.fontSize = '20px' })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true)
  await expect(page.getByRole('button', { name: '家庭資料' })).toBeVisible()
})

test('PWA Service Worker 可離線重新開啟既有規劃', async ({ page, context }) => {
  await page.getByRole('button', { name: '先使用展示資料體驗' }).click()
  await expect(page.getByRole('heading', { name: /35 年後約/ })).toBeVisible({ timeout: 15_000 })
  await page.evaluate(() => navigator.serviceWorker.ready)
  await context.setOffline(true)
  await page.reload()
  await expect(page.getByText('林家退休計畫')).toBeVisible()
  await context.setOffline(false)
})
