import { cleanup, fireEvent, render, screen, waitFor, act, within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { afterEach, describe, expect, it, vi } from 'vitest'
import { QuickAddAsset } from './QuickAddAsset'
import { DataPage } from './DataPage'
import { createDemoData } from '../application/planner-data'
import { buildQuickAsset, createQuickAssetDraft, type QuickAssetDraft } from '../application/quick-add-asset'
import { PlannerService } from '../application/planner-service'
import type { QuickLookupResult } from '../application/quick-asset-lookup'

afterEach(cleanup)
const service = new PlannerService({ load: async () => null, save: async () => undefined, clear: async () => undefined })
describe('Beta 新增互動', () => {
  it('可用鍵盤輸入負數小數報酬，完成後保存比例', async () => {
    const commit = vi.fn(async (draft: QuickAssetDraft) => Boolean(draft))
    const user = userEvent.setup()
    render(<QuickAddAsset data={createDemoData('2026-09-01')} onCommit={commit} onComplete={vi.fn()} onCancel={vi.fn()} />)
    await user.click(screen.getByRole('button', { name: /現金／存款/ }))
    await user.type(screen.getByLabelText('名稱'), '自訂現金')
    await user.type(screen.getByLabelText(/目前餘額/), '100')
    await user.click(screen.getByText('進階設定（選填）'))
    await user.click(screen.getByLabelText('自訂此筆三情境報酬'))
    await user.clear(screen.getByLabelText('保守年報酬（%）'))
    await user.type(screen.getByLabelText('保守年報酬（%）'), '-1.5')
    await user.click(screen.getByRole('button', { name: '檢查並繼續' }))
    await user.click(screen.getByRole('button', { name: '完成新增' }))
    expect(commit.mock.calls[0][0].customRates?.conservative).toBe('-0.015')
  })
  it('失敗保留草稿、阻止雙擊、可重試，僅成功才完成', async () => {
    let resolve!: (result: boolean) => void
    const commit = vi.fn().mockImplementationOnce(() => new Promise<boolean>((r) => { resolve = r })).mockResolvedValueOnce(true)
    const complete = vi.fn()
    render(<QuickAddAsset data={createDemoData('2026-09-01')} onCommit={commit} onComplete={complete} onCancel={vi.fn()} />)
    fireEvent.click(screen.getByRole('button', { name: /現金／存款/ }))
    fireEvent.change(screen.getByLabelText('名稱'), { target: { value: '生活費' } })
    fireEvent.change(screen.getByLabelText(/目前餘額/), { target: { value: '25000' } })
    fireEvent.click(screen.getByRole('button', { name: '檢查並繼續' }))
    fireEvent.click(screen.getByRole('button', { name: '完成新增' }))
    fireEvent.click(screen.getByRole('button', { name: '儲存中…' }))
    expect(commit).toHaveBeenCalledTimes(1)
    await act(async () => resolve(false))
    expect(screen.getByRole('alert')).toHaveTextContent('輸入已保留')
    expect(complete).not.toHaveBeenCalled()
    expect(screen.getByText(/生活費 ·/)).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: '完成新增' }))
    await waitFor(() => expect(complete).toHaveBeenCalledWith(true))
  })
  it('商品查詢晚到不覆蓋新代號；ETF 要確認股票或債券分類', async () => {
    let resolve!: (result: QuickLookupResult) => void
    const lookup = vi.fn(() => new Promise<QuickLookupResult>((r) => { resolve = r }))
    render(<QuickAddAsset data={createDemoData('2026-09-01')} onCommit={vi.fn()} onComplete={vi.fn()} onCancel={vi.fn()} lookup={lookup} />)
    fireEvent.click(screen.getByRole('button', { name: /投資商品/ }))
    fireEvent.change(screen.getByLabelText('資產種類'), { target: { value: 'etf' } })
    expect(screen.getByLabelText(/主要投資類別/)).toHaveValue('')
    fireEvent.change(screen.getByLabelText('商品代號'), { target: { value: '0050' } })
    fireEvent.click(screen.getByRole('button', { name: '查詢商品' }))
    fireEvent.change(screen.getByLabelText('商品代號'), { target: { value: '00679B' } })
    await act(async () => resolve({ name: '舊商品', fetchedAt: '2026-09-13', market: 'TWSE', messages: [], quote: { instrumentId: 'quick-draft', symbol: '0050', currency: 'TWD', price: '100', asOf: '2026-09-11', sourceId: 'test' } }))
    expect(screen.getByLabelText('名稱')).toHaveValue('')
    expect(screen.getByLabelText(/單價（TWD）/)).toHaveValue(null)
  })
  it('不動產只填估值、無行情，取消沒有保存', () => {
    const commit = vi.fn()
    const cancel = vi.fn()
    render(<QuickAddAsset data={createDemoData('2026-09-01')} onCommit={commit} onComplete={vi.fn()} onCancel={cancel} />)
    fireEvent.click(screen.getByRole('button', { name: /其他資產/ }))
    fireEvent.change(screen.getByLabelText('資產種類'), { target: { value: 'property' } })
    expect(screen.queryByLabelText('查詢市場')).not.toBeInTheDocument()
    expect(screen.queryByLabelText(/持有數量/)).not.toBeInTheDocument()
    expect(screen.getByLabelText('加入投資組合與長期預測')).not.toBeChecked()
    expect(screen.getByLabelText('加入投資組合與長期預測')).toBeDisabled()
    fireEvent.click(screen.getByRole('button', { name: '取消快速新增' }))
    expect(cancel).toHaveBeenCalledOnce()
    expect(commit).not.toHaveBeenCalled()
  })
  it('新舊入口共存，開關 Beta 不丟失舊表單草稿；舊編輯保存手動部位', async () => {
    const data = createDemoData('2026-09-01')
    const next = buildQuickAsset(data, { ...createQuickAssetDraft(data), name: '手動持股', quantity: '20', price: '50' })
    const change = vi.fn()
    const user = userEvent.setup()
    render(<DataPage data={next} summary={service.dashboard(next, 'household')} onChange={change} onQuickAdd={vi.fn()} />)
    await user.click(screen.getByRole('button', { name: '編輯 手動持股' }))
    await user.clear(screen.getByLabelText('資產名稱'))
    await user.type(screen.getByLabelText('資產名稱'), '手動持股改名')
    await user.click(screen.getByRole('button', { name: '快速新增資產 Beta' }))
    await user.click(screen.getByRole('button', { name: '取消快速新增' }))
    expect(screen.getByLabelText('資產名稱')).toHaveValue('手動持股改名')
    await user.click(screen.getByRole('button', { name: '儲存資產' }))
    expect(change.mock.calls[0][0].holdings).toEqual(next.holdings)
  })
  it('查價失敗可手動完成美元 ETF，不建立虛假行情', async () => {
    const data = createDemoData('2026-09-01')
    const commit = vi.fn(async (draft: QuickAssetDraft) => Boolean(draft))
    render(<QuickAddAsset data={data} onCommit={commit} onComplete={vi.fn()} onCancel={vi.fn()} lookup={async () => { throw new Error('離線，請手動填寫。') }} />)
    fireEvent.click(screen.getByRole('button', { name: /投資商品/ }))
    fireEvent.change(screen.getByLabelText('資產種類'), { target: { value: 'etf' } })
    fireEvent.change(screen.getByLabelText('查詢市場'), { target: { value: 'US' } })
    fireEvent.change(screen.getByLabelText('商品代號'), { target: { value: 'BND' } })
    fireEvent.click(screen.getByRole('button', { name: '查詢商品' }))
    await screen.findByText('離線，請手動填寫。')
    fireEvent.change(screen.getByLabelText('名稱'), { target: { value: '美債 ETF' } })
    fireEvent.change(screen.getByLabelText(/主要投資類別/), { target: { value: 'bond' } })
    fireEvent.change(screen.getByLabelText(/持有數量/), { target: { value: '10' } })
    fireEvent.change(screen.getByLabelText(/單價（USD）/), { target: { value: '70' } })
    fireEvent.change(screen.getByLabelText(/手動美元匯率/), { target: { value: '32' } })
    fireEvent.click(screen.getByRole('button', { name: '檢查並繼續' }))
    fireEvent.click(screen.getByRole('button', { name: '完成新增' }))
    await waitFor(() => expect(commit).toHaveBeenCalledOnce())
    const saved = buildQuickAsset(data, commit.mock.calls[0][0]!)
    expect(saved.assets.at(-1)).toMatchObject({ assetType: 'etf', allocationClass: 'bond', currentValue: { amount: '700.00', currency: 'USD' } })
    expect(saved.instruments).toEqual([])
  })
  it('最新 props 的既有資料變更仍保留', () => {
    const data = createDemoData('2026-09-01')
    const commit = vi.fn()
    const { rerender } = render(<QuickAddAsset data={data} onCommit={commit} onComplete={vi.fn()} onCancel={vi.fn()} />)
    fireEvent.click(screen.getByRole('button', { name: /現金／存款/ }))
    fireEvent.change(screen.getByLabelText('名稱'), { target: { value: '新的現金' } })
    const latest = structuredClone(data)
    latest.portfolios = []
    rerender(<QuickAddAsset data={latest} onCommit={commit} onComplete={vi.fn()} onCancel={vi.fn()} />)
    expect(within(screen.getByRole('region', { name: '快速新增資產 Beta' })).getByText('首次建立投資組合')).toBeInTheDocument()
    expect(screen.getByLabelText('名稱')).toHaveValue('新的現金')
  })
})
